services:
  reverse-proxy:
    image: traefik:v3.2
    container_name: mem_proxy
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    networks:
      - mem
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  client:
    image: mem_client
    container_name: mem_client
    build:
      context: client
    volumes:
      - ./client:/app
    networks:
      - mem
    command: npm run dev
    labels:
      - traefik.http.routers.client.rule=PathPrefix(`/`)
      - traefik.http.services.client.loadbalancer.server.port=3000

  server:
    image: mem_server
    container_name: mem_server
    build:
      context: server
    volumes:
      - ./server:/app
    networks:
      - mem
    command: flask --app app run --debug --host=0.0.0.0
    labels:
      - traefik.http.routers.server.rule=PathPrefix(`/api`)
      - traefik.http.services.server.loadbalancer.server.port=5000

networks:
  mem:
    driver: bridge
